### ISSUE TITLE
Proton namespace

### ISSUE THREAD

**Issue by BafS** [wjh825998772/region#1]
Hi wjhtime,

我是在ProtonMail (http://protonmail.com) 工作的程序员，我们最近想要在packagist.org上开源一些源代码，但是我查了一下，您现在拥有Proton这个名字的所有权。我们想请问您是否愿意将Proton这个名字让给我们使用。

非常感谢。

**Comment by BafS** [comment]
Any update :) ?

**Comment by BafS** [comment]
@wjhtime it would be great if you could give us an update

**Comment by BafS** [comment]
@wjhtime ping

**Comment by BafS** [comment]
@wjhtime ping ?

**Comment by wjhtime** [comment]
no, thanks

**Comment by BafS** [comment]
@wjhtime thanks for your answer, nevertheless there is only one package on "Proton" namespace with 17 installations, the last one is from 2019. Please let us know if you change your mind.

**Comment by BafS** [comment]
Hello @wjhtime, would it be possible to revisit your decision? Thank you in advance!
